name: haversine
description: Calculate geographic distance on earth having a pair of Latitude/Longitude points using the Haversine formula.
version: 1.0.2
homepage: https://www.yeradis.com
author: Yeradis P. Barbosa Marrero <yeradis@gmail.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.5.1+1
